const skills = [
  {
    id: 1,
    img: '1.gif',
    animation: 600,
    name: 'REAL-ESTATE-CLIENT',
    tec: ['React.js', 'react-redux'],
    description: "A real estate application that is created using react and consumes a rails API. Some of the features includes state management using react-redux, front end authentication using browser cookies and react-redux, and flash messages for displaying information while perfoming asyncronous actions.",
    src: 'https://real-estate-client.netlify.app/',
    github: 'https://github.com/wathigo/Real-Estate-Client',
  },
  {
    id: 2,
    img: '2.gif',
    animation: 800,
    name: 'COVID-19-STATS',
    tec: ['React', 'react-redux', 'react-globe-gl'],
    description: "A mobile web application that fetches and displays official covid-19 data. Some of the features includes ability to filter data and visualize the data on the globe.",
    src: 'https://official-covid-19-stats.netlify.app/',
    github: 'https://github.com/wathigo/covid-19-stats',
  },
  {
    id: 3,
    img: '3.png',
    animation: 600,
    name: 'BATTLESHIP',
    tec: ['JavaScript', 'HTML', 'CSS'],
    description: "A simple game that offers you two boards, user board, and a compuer board. User guesses the position of the ship on the computer board while the computer guesses the position of the ship on the user board. The player that attacks all the ships first wins.",
    src: 'https://rawcdn.githack.com/samgaco/battleship/99636649edc187e84328dea52993590378bfb4dc/dist/index.html',
    github: 'https://github.com/wathigo/battleship',
  },
  {
    id: 4,
    img: '4.png',
    animation: 800,
    name: 'CALCULATOR',
    tec: ['JavaScript', 'React'],
    description: "A simple mobile web application that implements simple arithmetic operation such as addition, substraction, division, and substraction.",
    src: 'https://fracalc.herokuapp.com/',
    github: 'https://github.com/wathigo/Calculator',
  },
  {
    id: 5,
    img: '5.gif',
    animation: 600,
    name: 'TIC-tac-toe',
    tec: ['JavaScript', 'DOM'],
    description: "A simple application made with vanilla JavaScript that allows you to play the Tic-tac=toe game. Some of the knowledge acquired includes DOM manipulation and event handling.",
    src: 'https://raw.githack.com/wathigo/Tic-tac-toe-js/master/index.html',
    github: 'https://github.com/wathigo/Tic-tac-toe-js',
  },
  {
    id: 6,
    img: '6.png',
    animation: 800,
    name: 'BookStore CMS',
    tec: ['React', 'React-redux'],
    description: "A simple application made with react-redux that allows you to create, remove or filter books",
    src: 'https://librairie.herokuapp.com/',
    github: 'https://github.com/wathigo/Bookstore',
  },
];

export default skills;
